# Jekyll configuration for Open SDG platform

baseurl: "/indicadores-ods-asturias"
remote_data_prefix: "https://sadeiasturias.github.io/asturias-datos/"
data_edit_url: http://prose.io/#sadeiasturias/asturias-datos/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#sadeiasturias/asturias-datos/edit/develop/meta/[id].md

# Replace this title as needed.
title: Indicadores de Asturias de los Objetivos de Desarrollo Sostenible
url: ""
data_dir: data
environment: production #staging

# The list of languages that are translated. The first one is the default.
languages:
  - es
  - en

decimal_separator: ',' # requires open-sdg@1.3.0 at least
accessible_tabs: true
accessible_charts: true
graph_color_set: accessible

# This makes sure that all pages have a language. 
#defaults:
#  -
#    scope:
#      path: ""
#    values:
#      language: "es"

#jekyll_get_json:
#  - data: translations
#    json: 'https://open-sdg.org/sdg-translations/translations.json'

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
# Recommended: set this to a particular "release" of Open SDG.
remote_theme: open-sdg/open-sdg@1.3.1  #open-sdg@1.1.0

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target  #goal-by-target-vertical
create_pages:
  pages:
    - folder: /
      layout: frontpage #frontpage-alt
    #- folder: /goals
    #  layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - filename: indicators.json
      folder: /
      layout: indicator-json
    - folder: /search
      layout: search

analytics:
  ga_prod: 'UA-150215-1' #general de sadei.es; 'G-K2V2BMPZL7' #específica para web ods 

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: info@sadei.es
  suggestions: info@sadei.es
  functional: info@sadei.es

# International Support
country:
  name: Asturias
  adjective: Asturian

# Dates for different languages
date_formats:
  standard:
    es: "%d-%m-%Y"
    en: "%b %d, %Y"

# Optionally set a title/body for the frontpage layout banner.
# It works fot he goals layout too.
frontpage_introduction_banner:
  title: frontpage.intro_title
  #description: frontpage.intro_body

# Optionally, for the frontpage layout, set a title and help text on top of the goals grid.
# The goals layout uses the frontpage variables "heading" and "instructions" automatically, 
# regardless of the settings below.
frontpage_goals_grid:
  title: frontpage.heading
  description: frontpage.instructions

frontpage_cards:
  - title: frontpage.download_all
    include: components/download-all-data.html
#  - title: frontpage.download_excel
#    content: |
#      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
#      cursus est sed dapibus.
#    button_label: Read more
#    button_link: https://example.com

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
# Use these to customise the main navigation.
# The "translation_key" refers to the key in the SDG Translations repository (or the file in your repository overriding it).
menu:
  - path: /  #/goals
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  #- path: /guidance
  #  translation_key: menu.guidance
  #- path: /faq
  #  translation_key: menu.faq
  #- path: /news
  #  translation_key: menu.updates

footer_menu:
  - path: mailto:info@sadei.es
    translation_key: menu.contact_us
  - path: https://twitter.com/sadeiAsturias
    translation_key: general.twitter
  - path: https://www.facebook.com/sadeiAsturias
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
#non_global_metadata: indicator.national_metadata
metadata_tabs:
  national:
    title: indicator.national_metadata
    blurb: indicator.national_metadata_blurb
#  - scope: global
#    title: indicator.global_metadata
#    description: indicator.global_metadata_blurb
#  - scope: sources
#    title: indicator.sources
#    description: ''

hide_empty_metadata: true

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme  
  - jekyll-open-sdg-plugins
  #- jekyll-get-json


# Apply any custom Javascript.
custom_js:
  - /assets/js/custom.js


# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
